parameters:
    emoe_guzzle.monolog_log_adapter.class: Emoe\GuzzleBundle\Log\MonologLogAdapter

services:
    emoe_guzzle.monolog_formatter:
        class: %guzzle.formatter.class%
        public: false
        arguments:
            - %emoe_guzzle.log.format%

    emoe_guzzle.monolog_log_adapter:
        class: %emoe_guzzle.monolog_log_adapter.class%
        public: false
        arguments:
            - '@monolog.logger'

    emoe_guzzle.request_monolog_middleware:
        class: %emoe_guzzle.request_logger_middlware.class%
        public: false
        arguments:
            - '@emoe_guzzle.monolog_log_adapter'
            - '@emoe_guzzle.stopwatch'
            - '@emoe_guzzle.monolog_formatter'

