parameters:
    guzzle.client.class: GuzzleHttp\Client
    guzzle.requesthandler.class: Emoe\GuzzleBundle\Handler\RequestHandler
    guzzle.handlerstack.class: GuzzleHttp\HandlerStack

services:
    guzzle.handlerstack:
        class: %guzzle.handlerstack.class%
        factory: [%guzzle.handlerstack.class%, create]
        public: false

    guzzle.requesthandler:
        class: %guzzle.requesthandler.class%
        arguments:
            - @guzzle.handlerstack
            - @debug.stopwatch

    guzzle.client:
        class: %guzzle.client.class%
        arguments:
            - handler: "@=service('guzzle.requesthandler').getHandlerStack()"