parameters:
    guzzle.client.class: GuzzleHttp\Client
    guzzle.profiler_request_middlware.class: Emoe\GuzzleBundle\Middleware\ProfilerRequestMiddleware
    guzzle.handler_stack.class: GuzzleHttp\HandlerStack

services:
    guzzle.handler_stack:
        class: %guzzle.handler_stack.class%
        public: false
        factory: [%guzzle.handler_stack.class%, create]

    guzzle.profiler_request_middleware:
        class: %guzzle.profiler_request_middlware.class%
        public: false
        arguments:
            - @debug.stopwatch

    guzzle.client:
        class: %guzzle.client.class%
        tags:
            - { name: guzzle.client }
